### ISSUE TITLE
ES5/ES6 support release tentative date? Any chances of releasing it this month?

### ISSUE THREAD

**Issue by hit436** [SumoLogic/elasticsearch-client#161]
I am using ES 2.3 with sumologic 1.0.29, we are migrating to ES5. Can we know the tentative date for the support of ES5/ES6 any chances of releasing this month?

**Comment by CCheSumo** [comment]
@hit436 This is an on going efforts from sumologic to move this client to ES6. Please refer to https://github.com/SumoLogic/elasticsearch-client/pull/159. There are some tech debts in the new release we would like to resolve since it is the only chance we can introduce breaking changes (unless we want to release another major version). I think it is reasonable to request the release by this month. Although I would re-direct to @Ankurkkhurana to answer it since he is the one primilary working on it atm.

**Comment by Ankurkkhurana** [comment]
The original PR is merged and all the existing functionality is supported (i.e. UT's are passing). There might be some more effort required to support new functionalities that are not yet supported in new  version of client. @hit436 You can try the current version of the client and can open issue if there is something in particular which is not working for you.

**Comment by Ankurkkhurana** [comment]
Please reopen if required. Closing this for now.

**Comment by hit436** [comment]
Hi, we actually moved to Elastic4S.
