### ISSUE TITLE
Make a plan for supporting ES 2.0

### ISSUE THREAD

**Issue by rcoh** [SumoLogic/elasticsearch-client#81]

**Comment by CCheSumo** [comment]
There are a list of breaking changes we would like to roll out in the open source elasticsearch client with the update. Here is the reference page for the 8 changes (issues) and the discussion board for the tasks breakdown (discussion board)
Some of the issues we would like to fix in the current open source client https://github.com/SumoLogic/elasticsearch-client
1. "search_type" -> "scan" is no longer supported https://github.com/SumoLogic/elasticsearch-client/issues/100
2. Use akka-http client instead of spray https://github.com/SumoLogic/elasticsearch-client/issues/84
3. Upgrade akka version to 2.4.14 https://github.com/SumoLogic/elasticsearch-client/pull/90
4. Upgrade scalatest and json4s-native https://github.com/SumoLogic/elasticsearch-client/issues/94
5. Upgrade ES to 5.1 https://github.com/SumoLogic/elasticsearch-client/issues/89
6. Remove `ExtendedQueryRoot`https://github.com/SumoLogic/elasticsearch-client/issues/80
7 Remove default value for "highlight" in ElasticJsonDocumen https://github.com/SumoLogic/elasticsearch-client/issues/77
8 Fix flaky test https://github.com/SumoLogic/elasticsearch-client/issues/72
9 Remove MultimatchQueryWithOptions and use MultimatchQuery https://github.com/SumoLogic/elasticsearch-client/issues/71
10 Fix Error in Json format parsing https://github.com/SumoLogic/elasticsearch-client/issues/65
11 _timestamp depreciated in 5.1

Currently working in progress
